POST http://localhost:3000/api/auth/signup 
Content-Type: application/json

{
  "email": "test@test1.com",
  "password": "testtesttest"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "testtesttest"
}

###

POST http://localhost:3000/api/sauces
Content-Type: application/json

{
  "name": "test sauce",
  "manufacturer": "test manufacturer",
  "description": "test description",
  "mainPepper": "test pepper",
  "spicy": true,
  "vegetarian": true,
  "vegan": true,
  "price": 10,
  "imageUrl": "test url"
}
